"""The reference-fit battery: ~10 fits chosen for coverage, not doctrine.

Each fit exercises a distinct slice of the effect matrix from the roadmap's
v1 tier: weapon system (projectile/hybrid/energy/missile/drone), tank type
(armor buffer, armor active+ancillary, shield buffer, shield active+ancillary,
passive regen), prop (AB/MWD), rigs, and hull bonuses (T1 and T2).

Charges are part of the fit — turret damage lives on the charge. All fits are
computed at all-V skills, uniform damage profile, unless the entry says
otherwise. Implants/boosters and an alpha-clone skill set are deliberately
absent from this first battery and tracked as follow-ups in the spike log.
"""

FITS = [
    {
        'name': 'rifter-ac-brawler',
        'ship': 'Rifter',
        'exercises': 'small projectile turrets, ancillary armor rep (paste), MWD sig bloom, T1 rig',
        'modules': [
            ('150mm Light AutoCannon II', 'Republic Fleet EMP S'),
            ('150mm Light AutoCannon II', 'Republic Fleet EMP S'),
            ('150mm Light AutoCannon II', 'Republic Fleet EMP S'),
            ('5MN Y-T8 Compact Microwarpdrive', None),
            ('Warp Scrambler II', None),
            ('X5 Enduring Stasis Webifier', None),
            ('Small Ancillary Armor Repairer', 'Nanite Repair Paste'),
            ('Gyrostabilizer II', None),
            ('Damage Control II', None),
            ('Small Projectile Burst Aerator I', None),
        ],
        'drones': [],
    },
    {
        'name': 'punisher-pulse-armor',
        'ship': 'Punisher',
        'exercises': 'small energy turrets (crystals), armor buffer, AB',
        'modules': [
            ('Small Focused Pulse Laser II', 'Scorch S'),
            ('Small Focused Pulse Laser II', 'Scorch S'),
            ('Small Focused Pulse Laser II', 'Scorch S'),
            ('1MN Afterburner II', None),
            ('Cap Recharger II', None),
            ('Damage Control II', None),
            ('200mm Steel Plates II', None),
            ('Multispectrum Energized Membrane II', None),
            ('Heat Sink II', None),
            ('Small Trimark Armor Pump I', None),
        ],
        'drones': [],
    },
    {
        'name': 'merlin-blaster-shield',
        'ship': 'Merlin',
        'exercises': 'small hybrid turrets, shield buffer, hull resist bonus',
        'modules': [
            ('Light Neutron Blaster II', 'Void S'),
            ('Light Neutron Blaster II', 'Void S'),
            ('Light Neutron Blaster II', 'Void S'),
            ('5MN Y-T8 Compact Microwarpdrive', None),
            ('Medium Shield Extender II', None),
            ('Warp Scrambler II', None),
            ('X5 Enduring Stasis Webifier', None),
            ('Magnetic Field Stabilizer II', None),
            ('Damage Control II', None),
            ('Small Core Defense Field Extender I', None),
        ],
        'drones': [],
    },
    {
        'name': 'caracal-rlml-shield',
        'ship': 'Caracal',
        'exercises': 'rapid light launchers (clip+long reload — sustained vs burst DPS split)',
        'modules': [
            ('Rapid Light Missile Launcher II', 'Caldari Navy Scourge Light Missile'),
            ('Rapid Light Missile Launcher II', 'Caldari Navy Scourge Light Missile'),
            ('Rapid Light Missile Launcher II', 'Caldari Navy Scourge Light Missile'),
            ('Rapid Light Missile Launcher II', 'Caldari Navy Scourge Light Missile'),
            ('Rapid Light Missile Launcher II', 'Caldari Navy Scourge Light Missile'),
            ('50MN Quad LiF Restrained Microwarpdrive', None),
            ('Large Shield Extender II', None),
            ('Multispectrum Shield Hardener II', None),
            ('Warp Disruptor II', None),
            ('Ballistic Control System II', None),
            ('Ballistic Control System II', None),
            ('Nanofiber Internal Structure II', None),
            ('Medium Core Defense Field Extender I', None),
        ],
        'drones': [],
    },
    {
        'name': 'vexor-drone-armor',
        'ship': 'Vexor',
        'exercises': 'drone DPS with hull drone bonus, DDAs (stacking on drones), armor buffer',
        'modules': [
            ('250mm Railgun II', 'Antimatter Charge M'),
            ('250mm Railgun II', 'Antimatter Charge M'),
            ('10MN Afterburner II', None),
            ('Warp Scrambler II', None),
            ('X5 Enduring Stasis Webifier', None),
            ('1600mm Steel Plates II', None),
            ('Multispectrum Energized Membrane II', None),
            ('Damage Control II', None),
            ('Drone Damage Amplifier II', None),
            ('Drone Damage Amplifier II', None),
            ('Medium Trimark Armor Pump I', None),
        ],
        'drones': [('Hammerhead II', 5)],
    },
    {
        'name': 'drake-ham-passive',
        'ship': 'Drake',
        'exercises': 'passive shield regen (purger rigs + SPRs), HAMs, hull resist bonus',
        'modules': [
            ('Heavy Assault Missile Launcher II', 'Scourge Rage Heavy Assault Missile'),
            ('Heavy Assault Missile Launcher II', 'Scourge Rage Heavy Assault Missile'),
            ('Heavy Assault Missile Launcher II', 'Scourge Rage Heavy Assault Missile'),
            ('Heavy Assault Missile Launcher II', 'Scourge Rage Heavy Assault Missile'),
            ('Heavy Assault Missile Launcher II', 'Scourge Rage Heavy Assault Missile'),
            ('Heavy Assault Missile Launcher II', 'Scourge Rage Heavy Assault Missile'),
            ('Large Shield Extender II', None),
            ('Large Shield Extender II', None),
            ('Multispectrum Shield Hardener II', None),
            ('10MN Afterburner II', None),
            ('Shield Power Relay II', None),
            ('Shield Power Relay II', None),
            ('Shield Power Relay II', None),
            ('Shield Power Relay II', None),
            ('Medium Core Defense Field Purger I', None),
            ('Medium Core Defense Field Purger I', None),
            ('Medium Core Defense Field Purger I', None),
        ],
        'drones': [('Hobgoblin II', 5)],
    },
    {
        'name': 'hurricane-arty-alpha',
        'ship': 'Hurricane',
        'exercises': 'medium artillery (volley/alpha vs DPS split), shield buffer, hull RoF bonus',
        'modules': [
            ('720mm Howitzer Artillery II', 'Republic Fleet EMP M'),
            ('720mm Howitzer Artillery II', 'Republic Fleet EMP M'),
            ('720mm Howitzer Artillery II', 'Republic Fleet EMP M'),
            ('720mm Howitzer Artillery II', 'Republic Fleet EMP M'),
            ('720mm Howitzer Artillery II', 'Republic Fleet EMP M'),
            ('720mm Howitzer Artillery II', 'Republic Fleet EMP M'),
            ('50MN Quad LiF Restrained Microwarpdrive', None),
            ('Large Shield Extender II', None),
            ('Multispectrum Shield Hardener II', None),
            ('Warp Disruptor II', None),
            ('Gyrostabilizer II', None),
            ('Gyrostabilizer II', None),
            ('Tracking Enhancer II', None),
            ('Nanofiber Internal Structure II', None),
            ('Medium Projectile Ambit Extension I', None),
            ('Medium Core Defense Field Extender I', None),
            ('Medium Core Defense Field Extender I', None),
        ],
        'drones': [('Warrior II', 5)],
    },
    {
        'name': 'abaddon-pulse-armor',
        'ship': 'Abaddon',
        'exercises': 'large energy turrets, deep armor buffer, hull resist bonus, cap-heavy fit',
        'modules': [
            ('Mega Pulse Laser II', 'Conflagration L'),
            ('Mega Pulse Laser II', 'Conflagration L'),
            ('Mega Pulse Laser II', 'Conflagration L'),
            ('Mega Pulse Laser II', 'Conflagration L'),
            ('Mega Pulse Laser II', 'Conflagration L'),
            ('Mega Pulse Laser II', 'Conflagration L'),
            ('Mega Pulse Laser II', 'Conflagration L'),
            ('Mega Pulse Laser II', 'Conflagration L'),
            ('100MN Afterburner II', None),
            ('Cap Recharger II', None),
            ('Cap Recharger II', None),
            ('Cap Recharger II', None),
            ('1600mm Steel Plates II', None),
            ('1600mm Steel Plates II', None),
            ('Multispectrum Energized Membrane II', None),
            ('Multispectrum Energized Membrane II', None),
            ('Damage Control II', None),
            ('Heat Sink II', None),
            ('Heat Sink II', None),
            ('Large Trimark Armor Pump I', None),
            ('Large Trimark Armor Pump I', None),
        ],
        'drones': [],
    },
    {
        'name': 'raven-cruise-active',
        'ship': 'Raven',
        'exercises': 'cruise missiles, active shield tank, ancillary-free sustain',
        'modules': [
            ('Cruise Missile Launcher II', 'Mjolnir Fury Cruise Missile'),
            ('Cruise Missile Launcher II', 'Mjolnir Fury Cruise Missile'),
            ('Cruise Missile Launcher II', 'Mjolnir Fury Cruise Missile'),
            ('Cruise Missile Launcher II', 'Mjolnir Fury Cruise Missile'),
            ('Cruise Missile Launcher II', 'Mjolnir Fury Cruise Missile'),
            ('Cruise Missile Launcher II', 'Mjolnir Fury Cruise Missile'),
            ('X-Large Shield Booster II', None),
            ('Multispectrum Shield Hardener II', None),
            ('Multispectrum Shield Hardener II', None),
            ('Shield Boost Amplifier II', None),
            ('100MN Afterburner II', None),
            ('Cap Recharger II', None),
            ('Ballistic Control System II', None),
            ('Ballistic Control System II', None),
            ('Ballistic Control System II', None),
            ('Capacitor Flux Coil II', None),
            ('Capacitor Flux Coil II', None),
            ('Large Capacitor Control Circuit I', None),
            ('Large Capacitor Control Circuit I', None),
            ('Large Capacitor Control Circuit I', None),
        ],
        'drones': [],
    },
    {
        'name': 'zealot-pulse-t2',
        'ship': 'Zealot',
        'exercises': 'T2 hull with role/skill bonuses, medium energy turrets, armor buffer',
        'modules': [
            ('Heavy Pulse Laser II', 'Scorch M'),
            ('Heavy Pulse Laser II', 'Scorch M'),
            ('Heavy Pulse Laser II', 'Scorch M'),
            ('Heavy Pulse Laser II', 'Scorch M'),
            ('Heavy Pulse Laser II', 'Scorch M'),
            ('10MN Afterburner II', None),
            ('Cap Recharger II', None),
            ('1600mm Steel Plates II', None),
            ('Multispectrum Energized Membrane II', None),
            ('Heat Sink II', None),
            ('Heat Sink II', None),
            ('Damage Control II', None),
            ('Medium Energy Collision Accelerator I', None),
            ('Medium Trimark Armor Pump I', None),
        ],
        'drones': [],
    },
    {
        'name': 'golem-bastion-shield',
        'ship': 'Golem',
        'exercises': 'bastion state: preMul resist chain beside postPercent hardener, '
                     'torpedo marauder, local shield boost bonus',
        'modules': [
            ('Torpedo Launcher II', 'Mjolnir Torpedo'),
            ('Torpedo Launcher II', 'Mjolnir Torpedo'),
            ('Torpedo Launcher II', 'Mjolnir Torpedo'),
            ('Torpedo Launcher II', 'Mjolnir Torpedo'),
            ('Bastion Module I', None),
            ('Multispectrum Shield Hardener II', None),
            ('X-Large Shield Booster II', None),
            ('Ballistic Control System II', None),
            ('Damage Control II', None),
        ],
        'drones': [],
    },
    {
        'name': 'phoenix-siege-torp',
        'ship': 'Phoenix',
        'exercises': 'siege state: weapon multiplier, immobility (speed 0 in panel)',
        'modules': [
            ('XL Torpedo Launcher II', 'Mjolnir XL Torpedo'),
            ('XL Torpedo Launcher II', 'Mjolnir XL Torpedo'),
            ('XL Torpedo Launcher II', 'Mjolnir XL Torpedo'),
            ('Siege Module II', None),
            ('Ballistic Control System II', None),
        ],
        'drones': [],
    },
    {
        'name': 'minokawa-triage',
        'ship': 'Minokawa',
        'exercises': 'triage state: remote rep amount and cycle bonuses on a FAX',
        'modules': [
            ('Capital Remote Shield Booster II', None),
            ('Triage Module II', None),
            ('Capital Shield Extender II', None),
        ],
        'drones': [],
    },
]
